#!/bin/bash

APPNAME='jupyter-notebook'

#echo "This script runs $APPNAME as daemon"

start_app(){
    pid=$( ps -ef |grep $APPNAME|grep -v grep |awk {'print $2'} )
    if [ -n "$pid" ];then 
        echo -e "$APPNAME is running ,pid is " $pid
        exit 1
    fi

    nohup $APPNAME 2>&1 | cat >/dev/null &
}

stop_app(){
    pid=$( ps -ef |grep $APPNAME|grep -v grep |awk {'print $2'} )
    if [ -n "$pid" ];then 
        kill -9 $pid
    else
        echo -e "$APPNAME is not running " 
        exit 1
    fi
}

print_status(){
    pid=$( ps -ef |grep $APPNAME|grep -v grep |awk {'print $2'} )
    if [ -z "$pid" ];then 
        echo -e "$APPNAME is not running " 
    else
        echo -e "$APPNAME is running,pid is " $pid
    fi
}


print_version(){
    $APPNAME --version
}

case "$1" in
    start)
        start_app
        sleep 1
        print_status
        ;;
    stop)
        stop_app
        sleep 1
        print_status
        ;;
    status)
        print_status
        ;;
    version)
        print_version
        ;;
    *)
        echo
        echo "Usage: $(basename "$0") (start|stop|status|version)"
        echo
esac

exit 0

